### ISSUE TITLE
Incorrect Number of attempted questions

### ISSUE THREAD

**Issue by sudo-Mystic** [nikhilmwarrier/jee-2024-scraper#10] opened 2024-02-08 00:50 UTC
I tried for 30 S 1 . its showing 43 Attempted which is wrong . actually attempted are 40 . there is difference of 3
![Screenshot_2024-02-08-06-13-37-258_com.brave.browser.png](https://github.com/nikhilmwarrier/jee-2024-scraper/assets/93476337/90ae2d76-2444-49d5-a68e-49df7a283d2a)
Actual Attempted (Correct)

![Screenshot_2024-02-08-06-19-01-556_com.kiwibrowser.browser.png](https://github.com/nikhilmwarrier/jee-2024-scraper/assets/93476337/d8837aed-18ca-4917-bdf2-da11ef7866b9)
Shown by scrapper (Incorrect)

not sure why this happened by you can look into it

**Comment by Enigma1309** [comment] 2024-02-08 04:49
duplicate of #5

**Comment by itsMathew** [comment] 2024-02-08 10:18
Can you try it here and let me know
https://deploy-preview-11--jeescraper2024.netlify.app/

**Comment by Enigma1309** [comment] 2024-02-08 10:51
> Can you try it here and let me know https://deploy-preview-11--jeescraper2024.netlify.app/

yeah i've already seen this PR and tried to lookup but to no avail it's not working,
it shows the correct amount of right questions but incorrect amount of attempted questions

**Comment by itsMathew** [comment] 2024-02-08 11:06
> > Can you try it here and let me know https://deploy-preview-11--jeescraper2024.netlify.app/
> 
> yeah i've already seen this PR and tried to lookup but to no avail it's not working,
> it shows the correct amount of right questions but incorrect amount of attempted questions

can you send me your response sheet (after removing all personal info from it)?

**Closed as completed** 2024-02-10 06:50 UTC
